name: CI/CD Tour-Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "~/tour-project"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/tour-project

            echo "Checking port 8088..."
            PORT_IN_USE=$(sudo lsof -t -i:8088 || true)
            if [ -n "$PORT_IN_USE" ]; then
              echo "Port 8088 is in use, stopping process..."
              sudo kill -9 $PORT_IN_USE || true
            fi

            echo "Stopping and removing old container..."
            docker stop tour-project || true
            docker rm tour-project || true

            echo "Building new Docker image..."
            docker build -t tour-project:latest .

            echo "Running new container on port 8088..."
            docker run -d --name tour-project -p 8088:8088 tour-project:latest

            echo "Cleaning up unused images..."
            docker image prune -f

            echo "Deployment successful!"
